### ISSUE TITLE
AZ-104 image download fails

### ISSUE THREAD

**Issue by b3n3w** [Ditectrev/CloudMaster-Swift#33]
**Describe the bug**
When downloading the AZ-104 course, the download stops with an error : question43.jpg couldn't be opened.

**Comment by b3n3w** [comment]
Download fails because of missing image in source folder. PR opened to fix image reference:
https://github.com/Ditectrev/Microsoft-Azure-AZ-104-Microsoft-Azure-Administrator-Practice-Tests-Exams-Questions-Answers/pull/2

**Comment by b3n3w** [comment]
FEATURE:

Implement better error handling when downloading courses. When image does not exist, skip image and show the missing image error after the course has downloaded completely. Might make sense to add a "Send debug log to developer button".

**Comment by danieldanielecki** [comment]
We're aligned on the error handling mechanism ;-) just added my notes to https://github.com/Ditectrev/Microsoft-Azure-AZ-104-Microsoft-Azure-Administrator-Practice-Tests-Exams-Questions-Answers/issues/1#issuecomment-2180889109
